# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "3.1.x"

  - task: DotNetCoreCLI@2
    displayName: "Test run"
    inputs:
      command: "test"
      projects: "**/*.csproj"
      testRunTitle: "TestRun"

  - task: DotNetCoreCLI@2
    displayName: "Publish Project"
    inputs:
      command: "publish"
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      arguments: --output $(Build.ArtifactStagingDirectory)

  - task: PublishPipelineArtifact@1
    displayName: "Publish PP Artifact"
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)"
      artifact: "Calculator"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_hrnanhrnanhrnan'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v1.0.2'
      assets: '$(Build.ArtifactStagingDirectory)/*.zip'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'